// VitePress build-time data loader for the error-codes page.
//
// The canonical source of truth is `docs/error-codes.data.json`,
// regenerated by `cargo run -p aube-codes --bin generate-error-codes-docs`
// (wired into `mise run render`). This loader reads that file at
// build time and inlines it into the page bundle, so the table on
// `/error-codes` always matches the registry without round-tripping
// markdown.
//
// Schema mirrors `crates/aube-codes/src/bin/generate_error_codes_docs.rs`:
//   {
//     errors:     CodeMeta[],
//     warnings:   CodeMeta[],
//     categories: { errors: string[]; warnings: string[] }
//   }
//
// where each `CodeMeta` is `{ name, category, description, exit_code }`
// and `categories[*]` lists the labels in first-seen order so the
// `<ErrorCodesTable>` component can render filter chips deterministically.
//
// `defineLoader`'s `watch` glob triggers a hot reload whenever the
// committed JSON changes — rerunning the generator updates the page
// without a `aube docs:dev` restart.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ESM-compatible equivalent of CJS `__dirname`. VitePress runs this
// loader through esbuild/Node in ESM mode, so `__dirname` isn't
// available and we resolve against `import.meta.url` instead.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const JSON_PATH = path.resolve(__dirname, "./error-codes.data.json");

export interface CodeMeta {
  name: string;
  category: string;
  description: string;
  /** `null` for warnings; `null` for errors that fall back to exit-code 1. */
  exit_code: number | null;
}

export interface ErrorCodesData {
  errors: CodeMeta[];
  warnings: CodeMeta[];
  categories: {
    errors: string[];
    warnings: string[];
  };
}

declare const data: ErrorCodesData;
export { data };

export default {
  watch: ["./error-codes.data.json"],
  load(): ErrorCodesData {
    const raw = fs.readFileSync(JSON_PATH, "utf8");
    return JSON.parse(raw) as ErrorCodesData;
  },
};
